application: playlistimporterforwikipedia
version: 1
runtime: go
api_version: go1

handlers:
- url: /.*
  script: _go_app
- url: /kickoffgenrediscovery
  script: _go_app
- url: /refreshgenrelist
  script: _go_app
