application: playlistimporterforwikipedia
version: 1
runtime: go
api_version: go1

handlers:
- url: /admin/startplaylistdiscovery
  script: _go_app
  login: admin
- url: /admin/discoverplaylists
  script: _go_app
  login: admin
- url: /.*
  script: _go_app
