application: playlistimporterforwikipedia
version: 1
runtime: go
api_version: go1

handlers:
- url: /admin/startplaylistdiscovery
  script: _go_app
- url: /admin/discoverplaylists
  script: _go_app
- url: /templates
  static_dir: playlistimporter/templates
  application_readable: true
- url: /.*
  script: _go_app
